# Default values for busybox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: busybox 
  pullPolicy: IfNotPresent
  tag: latest 
env:
  name1: first
  value1: "5"
  name2: second
  value2: "6"
  name3: third
  value3: "7"
service:
  name: busybox
  type: ClusterIP
  port: 32580 
resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
restartPolicy: Never
busyboxruntimeinsecs: 60
